env:
  TERM: xterm-256color

shell:
  program: zsh

window:
  dimensions:
    columns: 100
    lines: 40
  
  padding:
    x: 10
    y: 10
  
  dynamic_padding: false
  decorations: full
  startup_mode: Windowed

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Hack
    style: Regular

  bold:
    family: Hack
    style: Bold

  italic:
    family: Hack
    style: Italic

  size: 11.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: '0x232627'
    foreground: '0xfcfcfc'

    dim_foreground: '0xeff0f1'
    bright_foreground: '0xffffff'
    dim_background: '0x31363b'
    bright_background: '0x000000'

  normal:
    black: '0x232627'
    red: '0xed1515'
    green: '0x11d116'
    yellow: '0xf67400'
    blue: '0x1d99f3'
    magenta: '0x9b59b6'
    cyan: '0x1abc9c'
    white: '0xfcfcfc'

  bright:
    black: '0x7f8c8d'
    red: '0xc0392b'
    green: '0x1cdc9a'
    yellow: '0xfdbc4b'
    blue: '0x3daee9'
    magenta: '0x8e44ad'
    cyan: '0x16a085'
    white: '0xffffff'

  dim:
    black: '0x31363b'
    red: '0x783228'
    green: '0x17a262'
    yellow: '0xb65619'
    blue: '0x1b668f'
    magenta: '0x614a73'
    cyan: '0x186c60'
    white: '0x63686d'

bell:
  animation: Linear
  color: '0x232627'
  duration: 200

background_opacity: 1

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: false

debug:
  render_timer: false
  persistent_logging: false
  log_level: OFF
  print_events: false
  ref_test: false

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

key_bindings:
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: Q, mods: Command, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: F11, command: { program: "wmctrl", args: ["-r", ":ACTIVE:", "-b", "toggle,fullscreen" ] } }

